-- ##################### inicio tabelas ######################## --

-- drop table fabricante cascade;

create table fabricante (
    fab_cod bigint not null generated by default as identity,
    fab_nome varchar not null,
    constraint fabricante_fab_cod_pkey primary key (fab_cod),
	constraint fabricante_fab_nome_ukey unique (fab_nome)

);

insert into public.fabricante(fab_nome)
values ('Acura'), ('Alfa Romeo'), ('Aston Martin'), ('Audi'), ('BMW'),
    ('Bentley'), ('Buick'), ('Cadillac'), ('Chevrolet'), ('Chrysler'),
    ('Daewoo'), ('Daihatsu'), ('Dodge'), ('Eagle'), ('FIAT'), ('Ferrari'),
    ('Fisker'), ('Ford'), ('Freightliner'), ('GMC'), ('Genesis'), ('Geo'),
    ('HUMMER'), ('Honda'), ('Hyundai'), ('INFINITI'), ('Isuzu'), ('Jaguar'),
    ('Jeep'), ('Kia'), ('Lamborghini'), ('Land Rover'), ('Lexus'), ('Lincoln'),
    ('Lotus'), ('MAZDA'), ('MINI'), ('Maserati'), ('Maybach'), ('McLaren'),
    ('Mercedes-Benz'), ('Mercury'), ('Mitsubishi'), ('Nissan'), ('Oldsmobile'),
    ('Panoz'), ('Plymouth'), ('Polestar'), ('Pontiac'), ('Porsche'), ('Ram'),
    ('Rivian'), ('Rolls-Royce'), ('SRT'), ('Saab'), ('Saturn'), ('Scion'),
    ('Subaru'), ('Suzuki'), ('Tesla'), ('Toyota'), ('Volkswagen'), ('Volvo');

-- drop table favorito cascade;

create table favorito (
    fav_cod bigint not null generated by default as identity,
    fav_usu_cod bigint not null,
    fav_anu_cod varchar not null,
    constraint favorito_pkey primary key (fav_cod),
    constraint favorito_usu_cod_fkey foreign key (fav_usu_cod) references usuario (usu_cod),
    constraint favorito_anu_cod_fkey foreign key (fav_anu_cod) references anuncio (anu_cod)
);

-- drop table mensagem cascade;

create table mensagem (
    men_cod bigint not null generated by default as identity,
    men_anu_cod varchar not null,
    men_usu_cod bigint not null,
    men_texto varchar not null,
    constraint mensagem_pkey primary key (men_cod),
    constraint mensagem_usu_cod_fkey foreign key (men_usu_cod) references usuario (usu_cod),
	constraint mensagem_anu_cod_fkey foreign key (men_anu_cod) references anuncio (anu_cod)
);

-- ##################### fim tabelas ######################## --