-- ##################### inicio tabelas ######################## --

-- drop table fabricante cascade;

create table fabricante (
    fab_cod bigint not null generated by default as identity,
    fab_nome varchar not null,
    constraint fabricante_fab_cod_pkey primary key (fab_cod)
);

-- drop table favorito cascade;

create table favorito (
    fav_cod varchar not null,
    fav_usu_cod bigint not null,
    fav_anu_cod varchar not null,
    constraint favorito_pkey primary key (fav_cod),
    constraint favorito_usu_cod_fkey foreign key (fav_usu_cod) references usuario (usu_cod),
    constraint favorito_anu_cod_fkey foreign key (fav_anu_cod) references anuncio (anu_cod)
);

-- drop table mensagem cascade;

create table mensagem (
    men_cod varchar not null,
    men_anu_cod varchar not null,
    men_usu_cod bigint not null,
    men_texto varchar,
    constraint mensagem_pkey primary key (men_cod),
    constraint mensagem_usu_cod_fkey foreign key (men_usu_cod) references usuario (usu_cod),
	constraint mensagem_any_cod_fkey foreign key (men_anu_cod) references anuncio (anu_cod)
);

-- ##################### fim tabelas ######################## --